BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE NOTAS_ALUMNOS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN -- ORA-00942: tabla no existe
            RAISE;
        END IF;
END;
/

COMMIT;

--? 2. Eliminar procedimiento si existe
BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE INSERTAR_NOTAS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN -- ORA-04043: objeto no existe
            RAISE;
        END IF;
END;
/
--? 3. Crear tabla (10 notas)
CREATE TABLE NOTAS_ALUMNOS (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE_ALUMNO   VARCHAR2(100),

    NOTA1 NUMBER(5,2),
    NOTA2 NUMBER(5,2),
    NOTA3 NUMBER(5,2),
    NOTA4 NUMBER(5,2),
    NOTA5 NUMBER(5,2),
    NOTA6 NUMBER(5,2),
    NOTA7 NUMBER(5,2),
    NOTA8 NUMBER(5,2),
    NOTA9 NUMBER(5,2),
    NOTA10 NUMBER(5,2),

    SUMA            NUMBER(7,2),
    PROMEDIO        NUMBER(5,2),
    FECHA_REGISTRO  DATE DEFAULT SYSDATE
);

COMMIT;

--? 4. Crear procedimiento almacenado
CREATE OR REPLACE PROCEDURE INSERTAR_NOTAS (
    P_NOMBRE   IN VARCHAR2,

    P_N1 IN NUMBER, P_N2 IN NUMBER, P_N3 IN NUMBER, P_N4 IN NUMBER, P_N5 IN NUMBER,
    P_N6 IN NUMBER, P_N7 IN NUMBER, P_N8 IN NUMBER, P_N9 IN NUMBER, P_N10 IN NUMBER,

    P_SUMA IN NUMBER,
    P_PROM IN NUMBER
)
AS
BEGIN
    INSERT INTO NOTAS_ALUMNOS (
        NOMBRE_ALUMNO,
        NOTA1, NOTA2, NOTA3, NOTA4, NOTA5,
        NOTA6, NOTA7, NOTA8, NOTA9, NOTA10,
        SUMA, PROMEDIO
    ) VALUES (
        P_NOMBRE,
        P_N1, P_N2, P_N3, P_N4, P_N5,
        P_N6, P_N7, P_N8, P_N9, P_N10,
        P_SUMA, P_PROM
    );

    COMMIT;
END;

COMMIT;

-- inserts / .

INSERT INTO NOTAS_ALUMNOS (
    NOMBRE_ALUMNO,
    NOTA1, NOTA2, NOTA3, NOTA4, NOTA5,
    NOTA6, NOTA7, NOTA8, NOTA9, NOTA10,
    SUMA, PROMEDIO
) VALUES (
    'Juan Perez',
    4.0, 3.5, 4.2, 3.8, 4.5,
    4.1, 3.9, 4.3, 4.0, 3.7,
    40.0, 4.0
);

INSERT INTO NOTAS_ALUMNOS VALUES (
    DEFAULT, 'Maria Lopez',
    3.0, 3.5, 3.2, 3.8, 3.5,
    3.1, 3.9, 3.3, 3.0, 3.7,
    34.0, 3.4, SYSDATE
);

INSERT INTO NOTAS_ALUMNOS VALUES (
    DEFAULT, 'Carlos Ruiz',
    5.0, 4.8, 4.9, 5.0, 4.7,
    4.8, 5.0, 4.9, 5.0, 4.8,
    48.9, 4.89, SYSDATE
);

INSERT INTO NOTAS_ALUMNOS VALUES (
    DEFAULT, 'Ana Torres',
    2.5, 3.0, 2.8, 3.2, 3.0,
    2.9, 3.1, 3.0, 2.7, 3.3,
    29.5, 2.95, SYSDATE
);

COMMIT;

-- store procd / .
BEGIN
    INSERTAR_NOTAS('Luis Gomez',
        4,4,4,4,4, 4,4,4,4,4,
        40,4
    );

    INSERTAR_NOTAS('Sofia Ramirez',
        3,3,3,3,3, 3,3,3,3,3,
        30,3
    );

    INSERTAR_NOTAS('Diego Martinez',
        5,5,5,5,5, 5,5,5,5,5,
        50,5
    );

    INSERTAR_NOTAS('Laura Hernandez',
        2,2,2,2,2, 2,2,2,2,2,
        20,2
    );
END;
/

commit;

-- select
SELECT NOMBRE_ALUMNO, SUMA, PROMEDIO, FECHA_REGISTRO
FROM NOTAS_ALUMNOS
ORDER BY ID;

-- prueba masiva .
BEGIN
    FOR i IN 1..20 LOOP
        INSERTAR_NOTAS(
            'Alumno_' || i,
            3,4,5,3,4, 5,4,3,5,4,
            40,4
        );
    END LOOP;
END;
/

COMMIT;